name = "Weeny Hut (neoforge)"
author = "mpryor"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95372b9f9fc6e88af144624a8ea1e32bc5101994d8385c87d9545c4a5bf3d931"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
