name = "Weeny Hut (neoforge)"
author = "mpryor"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff4bc42e49f36a1a18673187b09548ff40139edee9075b96f123dfd5509d133d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
