name = "Weeny Hut (neoforge)"
author = "mpryor"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b53eb40b88699830630f60fd4da44dee756b77ba752fa0b7ce1313b61f51fc98"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
