name = "Weeny Hut (dev)"
author = "mpryor"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b8e15b85bcc229eb1c6c49df5e42316ee52be31a01b71721aeb7508114bbb05"

[versions]
fabric = "0.19.4"
minecraft = "1.20.1"
