name = "Weeny Hut (neoforge-dev)"
author = "mpryor"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be15a258e281bbc95c9b417b700d906bfcfab8a9e138e3d184a8fd690608ff74"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
