name = "Weeny Hut"
author = "mpryor"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfe98c2aec044529f7e435fa801bdcd808be0502dafa3e03d4dce8390ab75d1c"

[versions]
fabric = "0.19.4"
minecraft = "1.20.1"
